### ISSUE TITLE
Want to understand how so you handle audio.

### ISSUE THREAD

**Issue by sanchitminda** [bomberman30/AdvanceOS-for-cardputer#3]
Hi @bomberman30 , I want to know how do you handle MP3 Playback.  I own a Rom MP3Player, it used to work with Cardputer v1.1 but its not working with Adv Version, I earlier used ESP8266Audio Library but that seems to have a compatibility issue now and the ESP32audioI2S library is causing Out of memory issue. I'll be glad if you could help.

Kind Regards,
Sanchit

**Comment by personwithbeans** [comment]
I've been having the same issues, finaly managed to get one work that wasn't jumpy if that makes sense. Thanks for the little bit of guidance.

**Comment by sanchitminda** [comment]
c:\Users\sanch\OneDrive\Documents\Arduino\libraries\ESP8266Audio\src\AudioOutputPDM.cpp: In member function 'virtual bool AudioOutputPDM::begin()':
c:\Users\sanch\OneDrive\Documents\Arduino\libraries\ESP8266Audio\src\AudioOutputPDM.cpp:77:22: error: 'struct i2s_pdm_tx_slot_config_t' has no member named 'data_fmt'
   77 |     pdm_cfg.slot_cfg.data_fmt = I2S_PDM_DATA_FMT_PCM;
      |                      ^~~~~~~~
c:\Users\sanch\OneDrive\Documents\Arduino\libraries\ESP8266Audio\src\AudioOutputPDM.cpp:77:33: error: 'I2S_PDM_DATA_FMT_PCM' was not declared in this scope
   77 |     pdm_cfg.slot_cfg.data_fmt = I2S_PDM_DATA_FMT_PCM;
      |                                 ^~~~~~~~~~~~~~~~~~~~
Multiple libraries were found for "SD.h"
  Used: C:\Users\sanch\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\3.2.5\libraries\SD
  Not used: C:\Users\sanch\AppData\Local\Arduino15\libraries\SD
exit status 1

Compilation error: exit status 1


Getting this issue still, do you know what is fix for this

**Comment by bomberman30** [comment]
Try use 2.0.0 version of ESP8266Audio or 2.2 the new version not working for me too

**Comment by sanchitminda** [comment]
Thanks, But found a workaround for this and root cause as well, M5Stack is using old version of ESP-IDF Libraries(v5.4) we can simply copy the new version into 

Remove old files from this folder: "C:\Users\<User>\AppData\Local\Arduino15\packages\m5stack\tools\esp32-arduino-libs\idf-release_v5.4-858a988d-v1\esp32s3"

Copy Files from this folder : C:\Users\sanch\AppData\Local\Arduino15\packages\esp32\tools\esp32s3-libs\3.3.6

If you face issue with Hardware file compatibility as well then:
Remove old files from this folder: C:\Users\sanch\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\3.3.6
Copy Files from this folder : C:\Users\sanch\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.6

**Comment by bomberman30** [comment]
set any esp32 board after create the project see platfromIO.ini

here my platformIO.ini see in your's

[env:esp32-s3-devkitm-1]; this is just the name you can sey any name
platform = espressif32 ;the platformIO version
board = m5stack-stamps3 ; the board itself
framework = arduino 
;espressif32 @ 6.12.0 
board_build.flash_mode = qio ;faster then dio

monitor_speed = 115200 ; for serial monitor
upload_speed = 921600

**Comment by sanchitminda** [comment]
Thank you so much brother, I am also on same path but arduino ide is like taking lot of productive time in compiling. I wamt to make most out of my cardputer, if you want you can use my MP3 Player as well. to MP3 play files.

**Comment by sanchitminda** [comment]
@bomberman30 have you faced this? 
Compiling .pio\build\esp32-s3-devkitm-1\libd5e\ESP8266Audio\AudioOutputPDM.cpp.o
.pio/libdeps/esp32-s3-devkitm-1/ESP8266Audio/src/AudioOutputI2S.cpp:23:10: fatal error: driver/i2s_std.h: No such file or directory
 #include <driver/i2s_std.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
.pio/libdeps/esp32-s3-devkitm-1/ESP8266Audio/src/AudioOutputI2SNoDAC.cpp:23:10: fatal error: driver/i2s_std.h: No such file or directory
 #include <driver/i2s_std.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from .pio/libdeps/esp32-s3-devkitm-1/ESP8266Audio/src/AudioOutputPDM.cpp:22:
Compiling .pio\build\esp32-s3-devkitm-1\libd5e\ESP8266Audio\AudioOutputPWM.cpp.o
.pio/libdeps/esp32-s3-devkitm-1/ESP8266Audio/src/AudioOutputPDM.h:25:10: fatal error: driver/i2s_pdm.h: No such file or directory
 #include <driver/i2s_pdm.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32-s3-devkitm-1\libd5e\ESP8266Audio\AudioOutputI2S.cpp.o] Error 1
*** [.pio\build\esp32-s3-devkitm-1\libd5e\ESP8266Audio\AudioOutputI2SNoDAC.cpp.o] Error 1
*** [.pio\build\esp32-s3-devkitm-1\libd5e\ESP8266Audio\AudioOutputPDM.cpp.o] Error 1
